# Generated by Django 6.0 on 2025-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_description', models.TextField()),
                ('product_colors', models.CharField(choices=[('RD', 'RED'), ('WH', 'WHITE'), ('GRN', 'GREEN'), ('BL', 'BLUE')], max_length=3)),
            ],
        ),
    ]
